### ISSUE TITLE
[Request Details Page]: Request details screen is not scrollable if the request URL is very long

### ISSUE THREAD

**Issue by OmkarK45** [alexbrazier/react-native-network-logger#107]
**Describe the bug**
- When you have a request which involves a long URL, the request details page is not scrollable as the header takes up the most space.

**Expected behavior**
- Allow me to scroll to see the rest of the sections like Response headers, request headers etc

**Screenshots**
<img src="https://github.com/user-attachments/assets/ecd611d2-55c7-453e-a4c0-35cc95438ef2" width="400px" />

**Platform:**
- [x] iOS
- [x] Android

**Additional context** (My suggestions)
- Putting the page entire page in a scroll view OR 
- Truncate URL to 5-10 lines, if it's longer, add a view more CTA. Adding a view more button to the top header component should solve it

**Comment by alexbrazier** [comment]
Hi @OmkarK45, thanks for raising this. I've made a change in #108 which should hopefully resolve the issue.

It limits the number of lines displayed on the request list and restricts the height and adds a scrollview to the request details page.

**Comment by OmkarK45** [comment]
> Hi @OmkarK45, thanks for raising this. I've made a change in #108 which should hopefully resolve the issue.
> 
> It limits the number of lines displayed on the request list and restricts the height and adds a scrollview to the request details page.

Thanks a lott, I appreciate it
