### ISSUE TITLE
Conflict with `reactotron-react-native` library

### ISSUE THREAD

**Issue by leandrosimoes** [alexbrazier/react-native-network-logger#15]
Hi! First of all, awesome work on this library, it is amazing.

Well, I open this issue using the "Other" template because I really don't know if the problem that I found has some workaround.

As you can see in the image below, at this point in code, the library checks if the interceptor is enabled or not, and if it is already enabled, the code just returns:

![image](https://user-images.githubusercontent.com/5066378/87076168-bcfcfa00-c1f7-11ea-918b-2f71d4faef68.png)

So after debugging, I just check that the [reactotron-react-native](https://github.com/infinitered/reactotron-react-native/blob/375a5cfde3f223ddc7ef1f9a98056603038752df/src/plugins/networking.ts) library was enabling that by default, just by importing the library, and that was making the Logger skip the setup and because of that do not log any request.

What I did was remove the Reactotron and put it again manually just when I want to debug other things in my application.

So, I was wondering if there's any way to work around this conflict between these two libraries and make them work together.

Thanks!

**Comment by alexbrazier** [comment]
Hi, thanks for using the library and opening the issue. I've had a look through the react-native code and from what I can tell it looks like the way the `XHRInterceptor` is implemented you can only have one interceptor set at the same time.

If I removed the `isInterceptorEnabled` check, it would cause react-native-network-logger to override `reactotron-react-native` (or the other way round depending on which gets loaded first), which I'm not sure is what you would want either.

I'm not really sure what can be done about this - open to any suggestions.

**Comment by leandrosimoes** [comment]
Hi @alexbrazier, thanks for the answer. Well, I will think about it and see if I found another solution for that. So I will close this issue and if I found some workaround I let you know, ok?

Thanks again!

**Comment by yoan-guiz** [comment]
Hello, thank you for this very useful library
Did you find any way to be able to use it with reactotron please?

**Comment by alexbrazier** [comment]
I think it would require a code change. Only thing I can think of is adding a flag to `enableNetworkLogger` to force it to be enabled, then you could manually call it from inside your app. If you did it would disable network logging on reactotron though.

**Comment by alexbrazier** [comment]
This issue should now be fixed. You'll need to start the logger with the `forceEnable: true` option. This will override any other network interceptors that are running.

```ts
startNetworkLogging({ forceEnable: true });
```
