### ISSUE TITLE
Having a small problem importing package

### ISSUE THREAD

**Issue by ZachDiscover** [alexbrazier/react-native-network-logger#16]
When I try importing your package into my currently existing react-native project I get a problem from the package saying in the import part there is a syntax error with an unexpected token. All I did was yarn add react-native-network-logger then tried running my project again. Thank you for any help! I have attached an image of the error message.     
![Screen Shot 2020-07-10 at 3 04 10 PM](https://user-images.githubusercontent.com/50955084/87194634-f51b4000-c2be-11ea-8e1f-bb24759c3b52.png)

**Comment by alexbrazier** [comment]
Hi @ZachDiscover, thanks for opening the issue. Are you using typescript in your project, and if so what version? Also what version of metro bundler or expo are you using?

**Comment by alexbrazier** [comment]
I'm thinking this might fix the issue, although I haven't managed to recreate it #17

**Comment by ZachDiscover** [comment]
Sorry for the slow response! I didn't think you would get back so quickly so thank you on that! I just got into work today and will get back to you on that, thanks for helping and even looking into it at all!

**Comment by ZachDiscover** [comment]
Hey man just wanted to let you know that the fix that you did was able to get it running, thank you for your help!

**Comment by alexbrazier** [comment]
Perfect, I'll push a new version with the fix shortly

**Comment by alexbrazier** [comment]
Fix release in [1.4.1](https://github.com/alexbrazier/react-native-network-logger/releases/tag/v1.4.1)
