### ISSUE TITLE
Export all Logs

### ISSUE THREAD

**Issue by Spencer-Yoder** [alexbrazier/react-native-network-logger#27]
**Feature Request**

Having the ability to export the full list of logged request to a JSON file stored locally on the device.

I know the project right now doesn't have any dependencies (that's really nice), but the easiest and most practical way to do it would include using a package like `react-native-fs`.

**Additional context**

**Comment by alexbrazier** [comment]
Good idea @Spencer-Yoder. I'm open to adding dependencies to the project, although quite keen not to add native dependencies like `react-native-fs` as the would stop the library working with expo.

There is already an option to "Share full request" for each individual request, which then gives you the option to save to a file, email or copy etc. I'm not sure if there is a limitation on how long the share string can be, but we could potentially use that to share all requests without installing anything?
