### ISSUE TITLE
Single Request not showing as pending

### ISSUE THREAD

**Issue by Spencer-Yoder** [alexbrazier/react-native-network-logger#32]
**Describe the bug**

When only one request is made at a time, it does not show up a pending, and will only be added to the list after it completes.  
If more then one API request is created at the same time, then the pending API request will show as pending.

**Expected behavior**

When only 1 API request is fired, then it should show up in the request list as pending. Once the request is completed the status number and time should be updated.

**Screenshots**

It was easier for me to post videos on my fork and screenshots

Working as expected: https://github.com/Spencer-Yoder/react-native-network-logger/blob/Git-issue/Two%20Request(Working%20as%20expected).mp4
Defect: https://github.com/Spencer-Yoder/react-native-network-logger/blob/Git-issue/Single%20Request(Defect).mp4

**Platform:**
- [ ] iOS - I have not tested on iOS
- [x] Android - Tested on Emulator and Physical Device

**Additional context**

Checked out master at v1.7.0 and ran the example project
It is easy to recreate it for me, if there is a delay in the request. Using `https://postman-echo.com/delay/5` worked for me.

**Comment by alexbrazier** [comment]
Thanks for opening a detailed bug report @Spencer-Yoder. The issue should be fixed in #33 which will be in the next release.
