### ISSUE TITLE
is it possible to show console.log ?

### ISSUE THREAD

**Issue by KingAmo** [alexbrazier/react-native-network-logger#54]
**Feature Request**

i want to see console log in release build, is it possible to show console log like [Vconsole](https://github.com/Tencent/vConsole) ?

**Comment by alexbrazier** [comment]
It's not currently possible to view logs. I think that feature probalby belongs in a separate library as it is unrelated to network logging.

You could probably quite easily mock something up locally by using a custom logger (or overriding the default console log). There may also be some other libraries out there that already do this.

Something like:

```jsx
const logs = []
const logger = (...messages) => {
  console.log(...messages)
  logs.push(messages)
}

const LogViewer = () => (
  <View>
    {logs.map(log => <Text>{log.join(' ')}</Text>)}
  </View>
)


logger('Something to log')
```
