### ISSUE TITLE
Response Body not rendering

### ISSUE THREAD

**Issue by micnguyen** [alexbrazier/react-native-network-logger#8]
**Describe the bug**
- When launching the network debug and clicking onto a request, it does not show the response body even though the request was successful.
- However, it does show a large chunk of space where the response would have been.

**Expected behavior**
- Should show the response body

**Screenshots**
<img width="584" alt="Screen Shot 2020-06-25 at 9 04 58 pm" src="https://user-images.githubusercontent.com/919166/85708645-be262580-b727-11ea-8410-b3c95978a6e3.png">

**Platform:**
- [x] iOS
- [ ] Android

**Additional context**

**Comment by alexbrazier** [comment]
Hi @micnguyen, thanks for the report! I'm assuming the response body is very large, and that is causing a rendering issue?

I will probably need to find a way to efficiently render the text, as at the moment it all just goes straight into a `Text` component.

**Comment by alexbrazier** [comment]
@micnguyen it should be fixed in `1.3.2` by #9. If it's is still an issue the feel free to reopen this.

**Comment by micnguyen** [comment]
Thanks for he prompt fix in this. I can confirm on the latest version that my response body is rendering.
